### ISSUE TITLE
Failing turbo visits

### ISSUE THREAD

**Issue by georgekettle** [domchristie/turn#1]
I found that when I added turn to my rails 7 project, it worked until page transitions were too quick. So I removed some classes on html element when initialising the Turn class instance.

And also added export default on the class in order to import it in my application.js

There may be a better solution to this, I'm just adding my contribution :)

`export default class Turn {
  constructor (action) {
    // ...
    this.removeClasses('enter');
    this.removeClasses('exit');
  }`

**Comment by domchristie** [comment]
Thanks @georgekettle! I've fixed this in https://github.com/domchristie/turn/commit/4fc5dd1fee5ca674ffd58a2796774d62cd4c45de.

**Comment by georgekettle** [comment]
Thanks so much @domchristie Great work on this project, it's been very helpful for me 👍
